apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-agent
  namespace: otel
  labels:
    app: opentelemetry
    component: otel-agent
data:
  otel-agent-config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      opencensus:
    exporters:
      otlp:
        endpoint: "otel-collector.otel.svc.cluster.local:4317"
        insecure: true
      logging:
        loglevel: debug
    processors:
      batch:
      memory_limiter:
        # 80% of maximum memory up to 2G
        limit_mib: 400
        # 25% of limit up to 2G
        spike_limit_mib: 100
        check_interval: 5s
    extensions:
      pprof:
        endpoint: :1777
      zpages:
        endpoint: :55679
      health_check:
      memory_ballast:
        size_mib: 165
    service:
      extensions: [health_check, pprof, zpages, memory_ballast]
      pipelines:
        traces:
          receivers: [opencensus, otlp]
          exporters: [otlp, logging]
          processors: [batch, memory_limiter]
        metrics:
          receivers: [opencensus, otlp]
          exporters: [logging,otlp]
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-agent
  namespace: otel
  labels:
    app: opentelemetry
    component: otel-agent
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-agent
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-agent
    spec:
      containers:
      - command:
          - "/otelcol"
          - "--config=/conf/otel-agent-config.yaml"
        image: otel/opentelemetry-collector-dev:latest
        name: otel-agent
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 1777 # pprof extenstion port
        - containerPort: 55679 # ZPages port.
        - containerPort: 13133 # health_check extension port
        - containerPort: 8888  # Metrics port
        - containerPort: 55678 # OpenCensus receiver port for pometheus Metrics
        - containerPort: 4317 # Default endpoint for OpenTelemetry receiver.
        #- containerPort: 55680 # Default OpenTelemetry receiver port.
        volumeMounts:
        - name: otel-agent-config-vol
          mountPath: /conf
        livenessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
        readinessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
      volumes:
        - configMap:
            name: otel-agent
            items:
              - key: otel-agent-config
                path: otel-agent-config.yaml
          name: otel-agent-config-vol
---
apiVersion: v1
kind: Service
metadata:
  name: otel-agent
  namespace: otel
  labels:
    app: opentelemetry
    component: otel-agent
    type: headless
spec:
  clusterIP: None
  selector:
    app: opentelemetry
    component: otel-agent
  ports:
    - name: pprof
      protocol: TCP
      port: 1777
      targetPort: 1777
    - name: zpages
      protocol: TCP
      port: 55679
      targetPort: 55679
    - name: health-check
      protocol: TCP
      port: 13133
      targetPort: 13133
    - name: metrics
      protocol: TCP
      port: 8888
      targetPort: 8888
    - name: opencensus-receiver
      protocol: TCP
      port: 55678
      targetPort: 55678
    - name: otlp # Default endpoint for OpenTelemetry receiver.
      port: 4317
      protocol: TCP
      targetPort: 4317
